[project]
name = "mlx-wrapper"
version = "1.0.0"
description = "Simple Object-oriented wrapper around 42 school's MiniLibX"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mlx",
    "flake8>=7.3.0",
    "mypy>=2.3.1",
    "numpy>=2.5.2",
    "pillow>=12.3.0",
    "lxml>=6.1.3",
]

[tool.uv.sources]
mlx = { path = "./mlx-2.4-py3-none-any.whl" }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.mypy]
disable_error_code = ["import-untyped"]

[tool.hatch.build.targets.wheel]
packages = ["mlx_wrapper"]
