[project]
name = "mlx-wrapper"
version = "1.0.0"
description = "MiniLibX simple wrapper to abstract window interaction and raw data manipulation"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mlx",
]

[tool.uv.sources]
mlx = { path = "mlx-2.2-cp313-cp313-linux_x86_64.whl" }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
