[project]
name = "mlx-wrapper"
version = "1.0.0"
description = "Simple Object-oriented wrapper around 42 school's MiniLibX"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mlx",
    "numpy>=2.5.2",
]

[tool.uv.sources]
mlx = { path = "mlx-2.2-cp313-cp313-linux_x86_64.whl" }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["mlx_wrapper"]
